version: '3.11'

services:
  mysql:
    image: mysql/mysql-server:8.0
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_DATABASE=test

  app:
    build: .
    volumes:
      - ./:/app:rw,cached
    environment:
      # preserve bash history from devcontainer
      - PROMPT_COMMAND=history -a
      - HISTFILE=/app/.bash-history
